Water: 0
Wind:
  - 0.2
  - 1.0
Worm:
  - 0
  - 0.5
  - 0.5
  - 0
  - 2.0
  - 2.0
  - 6.0
  - 0.5
  - 4.0
  - 2
  - 1
  - 25
Girder:
  - 0.8
Bazooka:
  - 10
  - 0.25
  - 50
  - 6.0
  - 2.0
Mortar:
  - 10
  - 0.25
  - 50
  - 4.0
  - 2
  - 6
  - 35.0
  - 1.0
  - 10
GreenGrenade:
  - 10
  - 0.25
  - 0.5
  - 30
  - 2
  - 2
RedGrenade:
  - 10
  - 0.25
  - 0.5
  - 30
  - 2
  - 2
  - 6
  - 35
  - 1
  - 10
Banana:
  - 10
  - 0.25
  - 1
  - 70
  - 2
  - 4
HolyGrenade:
  - 10
  - 0.25
  - 0.5
  - 110
  - 2
  - 8
Dynimite:
  - 0.25
  - 0
  - 50
  - 2
  - 4
Bate:
  - 10
  - 10
AirAttack:
  - 1.0
  - 0.25
  - 40
  - 420
  - 2
  - 2
