Water: 0
Wind:
  - 0.2
  - 10
Worm:
  - 0
  - 1
  - 1
  - 0
  - 0.2
  - 1
  - 0.5
  - 0.2
  - 1.2
  - 2
  - 1
  - 25
Girder:
  - 0.8
Bazooka:
  - 2
  - 0
  - 50
  - 10
  - 5
Mortar:
  - 2
  - 0
  - 50
  - 10
  - 5
  - 6
  - 2
  - 0
  - 10
  - 10
  - 5
GreenGrenade:
  - 2
  - 0.5
  - 30
  - 10
  - 5
RedGrenade:
  - 2
  - 0.5
  - 30
  - 10
  - 5
  - 6
  - 2
  - 0.5
  - 10
  - 10
  - 5
Banana:
  - 4
  - 1
  - 70
  - 10
  - 5
HolyGrenade:
  - 8
  - 0.5
  - 110
  - 10
  - 5
Dynimite:
  - 4
  - 0
  - 50
Bate:
  - 10
AirAttack:
  - 2
  - 0
  - 40
  - 10
  - 5