Water: 0
Wind:
  - 0.2
  - 10
Worm:
  - 0
  - 1
  - 1
  - 0
  - 0.2
  - 1
  - 0.5
  - 0.2
  - 1.2
  - 2
  - 1
  - 25
Small Girder:
  - 0.4
  - 1.5
Large Girder:
  - 0.4
  - 3
Bazooka:
  - 10
  - 2
  - 50
  - 2
  - 2
Mortar:
  - 10
  - 2
  - 50
  - 2
  - 2
  - 6
  - 5
  - 1
  - 10
GreenGrenade:
  - 10
  - 2
  - 0.5
  - 30
  - 2
  - 2
RedGrenade:
  - 10
  - 2
  - 0.5
  - 30
  - 2
  - 2
  - 6
  - 5
  - 1
  - 10
Banana:
  - 10
  - 2
  - 1
  - 70
  - 2
  - 4
HolyGrenade:
  - 10
  - 2
  - 0.5
  - 110
  - 2
  - 8
Dynimite:
  - 1
  - 0
  - 50
  - 2
  - 4
Bate:
  - 10
  - 10
AirAttack:
  - 10
  - 2
  - 40
  - 420
  - 2
  - 2